language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2

gemfile:
  - Gemfile

matrix:
  fast_finish: true

script:
  - ruby tests/oneandone/test_servers.rb
  - ruby tests/oneandone/test_images.rb
  - ruby tests/oneandone/test_firewalls.rb
  - ruby tests/oneandone/test_shared_storages.rb
  - ruby tests/oneandone/test_load_balancers.rb
  - ruby tests/oneandone/test_monitoring_policies.rb
  - ruby tests/oneandone/test_public_ips.rb
  - ruby tests/oneandone/test_private_networks.rb